spring.application.name=SpringBootApi
#Теги та колекції: Створення власних полиць ("Прочитати", "Улюблене", "Для роботи").

server.port=8080

#cegiy92214@inreur.com
#cegiy92214@inreur.comQ
# Database connection properties
#spring.datasource.url=jdbc:postgresql://ep-weathered-butterfly-ap9qlonj-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_0s6VdDGkjPhi&sslmode=require&channelBinding=require
#spring.datasource.username=admin
#spring.datasource.password=secretStrashnyiOchen
spring.datasource.url=jdbc:postgresql://18.196.181.175:5399/mydb

spring.datasource.username=admin

spring.datasource.password=secretStrashnyiOchen

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# MinioSettings


minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=s3drive