spring.application.name=SpringBootApi

server.port=8080

#spring.datasource.url=jdbc:postgresql://ep-late-art-apc24rla-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_q3cToU9VbDyS&sslmode=require&channelBinding=require
spring.datasource.url=jdbc:postgresql://18.196.181.175:5399/mydb
spring.datasource.username=admin
spring.datasource.password=secretStrashnyiOchen
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# MinioSettings
minio.endpoint=http://18.196.181.175:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=s3drive


spring.web.error.include-message=always